### PR TITLE
Osm Hints

### PR DESCRIPTION
**Pull request by kpwebb**
Added a few possible changes to OSMLR spec to include hints to OSM way, node and sequence IDs.

The node and way IDs don't supplant the OSMLR referencing strategy, they just offer additional context and may assist when matching directly to an OSM basemap. 

The sequence ID seems more important to help ascertain the age/provenance of the OSM data used to generate the OSMLR tile. That said, curious if there are other strategies already used by other OSM-derived vector tiles that would work better.

### CODE REVIEW

**Comment by zerebubuth** [comment]
We had deliberately avoided including OSM IDs in the spec, as the information in the descriptors should be sufficient to match the geometry unambiguously. Additionally, OSM IDs can be misleading if they are re-used for different "shapes", for example when ways are split to introduce different properties along sections of the line. For example, we already merge across bridges, which is a property that has no bearing on traffic.

The segment descriptors are designed to be immutable, which allows us to keep the segment IDs compact over time, and make use of data which is being sent from reporters referencing older versions of the segment definitions. Adding OSM IDs means that there's another cause for descriptors to change, and therefore less continuity between versions of the segment definitions.

I think adding connectivity information could be useful, but my feeling is that OSM IDs could be helpful to a small number of users at the cost of being disruptive to all users.

**Comment by dnesbitt61** [comment]
To add to Matt's comments:
We do not store OSM node Ids within Valhalla and since we are creating OSMRL segment definitions from Valhalla tiles we do not have a simple way of adding node Ids.

I agree that some form of identifying the version/age of the tile data is required. By sequence Id are you referring to the OSM changeset Id (if so this need to be 64 bits). Valhalla does store a changeset Id so we could use this. But I wonder if a more generic version string would be better?

**Comment by zerebubuth** [comment]
> By sequence Id are you referring to the OSM changeset Id

I think @kpwebb meant the [sequence number used in OSM (minutely) replication diffs](https://wiki.openstreetmap.org/wiki/Planet.osm/diffs). Unfortunately, this number is not guaranteed to be stable in the long run, and might get reset for disaster recovery or across changes in the API version. A source data timestamp, although less precise, might be more human readable and stable in the long run.

**Comment by kpwebb** [comment]
@dnesbitt61 & @zerebubuth Thanks! I was going back and forth between changeset and sequence numbers, but wasn't sure what you were tracking in your tile generation workflow.

If changeset ID works for you as an easily defined checkpoint on the OSM state that generated the tile, that's great! 

Timestamps could also work, but seems kind of imprecise. 

As for the risk with OSM Way and Node IDs, completely understood. The point about immutability is pretty key. 

If desired, I can change this PR to drop the way/nodes and update the Tile def to include uint64 for changeset ID.

**Comment by zerebubuth** [comment]
Unfortunately, changeset IDs are potentially even less precise than timestamps. A changeset is not an atomic upload, and can be kept open for up to 24h as long as new edits are added to it. In practice, almost all changesets consist of a single upload and are effectively atomic, but it's not guaranteed.

It's a problem that I'd like to address in future versions of the OSM API, but that might be at an indefinite time in the future.

In the meantime, the best way of indicating a particular point in time for an OSM snapshot (i.e: planet or diff) is to pick the largest node ID that's at version 1. Since that's an event which happens only once, it's easy to tell whether diffs or planet files occurred before or after it. However, it's not very useful to anyone who wants to figure out which planet file to download, or which year that data file corresponds to, without having to go look up the node (or diff, or changeset). 

That's why I think that taking the timestamp of the data (which planet files have in their header - it's the maximum timestamp of all the elements in the file) is the most useful, although not completely precise.

**Comment by kpwebb** [comment]
@zerebubuth got it -- let's go with timestamps! 

 But I assume we'd show the timestamp of the last update, not the original planet file, correct?

Again, not sure how you all maintain updates in Valhalla -- projects I've worked on in the past were syncing minutely update files against an original planet ingest. Hopefully the timestamp being tracked internally corresponds to something close to the timestamp of a nearby minutely update?

**Comment by dnesbitt61** [comment]
@kpwebb - We have opened a separate PR that includes a timestamp for creation of the OSMLR tile (so we can know age of the tile) as well as using the OSM changeset Id. Even though this might not exactly match to an OSM planet it will match to a particular Valhalla data set and give a rough approximation of the OSM planet data used.

**Comment by drewda** [comment]
Closing in favor of https://github.com/opentraffic/osmlr-tile-spec/pull/4

**Pull request closed without merging**
